FROM node:lts-alpine3.17 AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

FROM base AS builder

WORKDIR /app

COPY . .
RUN CI=true pnpm install --frozen-lockfile
RUN CI=true pnpm run build:node

FROM base AS runner

WORKDIR /app

COPY --from=builder /app/dist/ ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/prisma/ ./prisma

CMD ["sh", "-c", "npm run db:deploy && npm run start:node"]
